on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install package
        run: pip install -e .
      - name: Install test dependencies
        run: pip install -r requirements-dev.txt
      - name: Lint
        run: flake8 .
      - name: Run tests
        run: pytest --cov=sksearchspace --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
  publish:
    name: Publish distributions to PyPI
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Setup up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install twine
        run: |
          python -m pip install --upgrade pip
          pip install twine wheel
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@186232109eade3d22bfe1bca29ac9a1312598511
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
